language: c
sudo: required
dist: trusty
script: ./travis-tool.sh run_tests

before_script:
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install -y gdal-bin libgdal-dev libgdal1-dev netcdf-bin libproj-dev libv8-dev
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh install_r leaflet
  - ./travis-tool.sh install_deps

after_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - Rscript -e 'covr::codecov()'

env:
   global:
     - R_LIBS="http://cran.rstudio.com"
     - R_BUILD_ARGS="--no-build-vignettes --no-manual"
     - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
     - _R_CHECK_FORCE_SUGGESTS_=FALSE

notifications:
  email:
    on_success: never
    on_failure: never
